### ISSUE TITLE
LookupError: Explicit mode set and ruleset plone.content.dynamic not found

### ISSUE THREAD

**Issue by arky** [collective/collective.volto.dropdownmenu#6]
Z3c.caching throws following error when it encounters the following line. Commenting the lines seems to resolve the issue: 

https://github.com/collective/collective.volto.dropdownmenu/blob/9fdb20c27eae564eeeecb380836ed6c462cfdc6f/src/collective/volto/dropdownmenu/restapi/dropdown_menu/configure.zcml#L15

```
$ ./bin/instance fg
/home/arky/Code/Plone/Plone-5/eggs/multipart-0.1.1-py3.9.egg/multipart.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import MutableMapping as DictMixin
2022-01-05 14:48:57,708 INFO    [chameleon.config:38][MainThread] directory cache: /home/arky/Code/Plone/Plone-5/var/cache.
/home/arky/Code/Plone/Plone-5/eggs/Products.StandardCacheManagers-4.0.3-py3.9.egg/Products/StandardCacheManagers/AcceleratedHTTPCacheManager.py:35: DeprecationWarning: rfc1123_date is deprecated. Please import from zope.datetime. This backwards compatibility import will go away in Zope 6.
  from App.Common import rfc1123_date
/home/arky/Code/Plone/Plone-5/eggs/pyScss-1.3.7-py3.9-linux-x86_64.egg/scss/types.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
/home/arky/Code/Plone/Plone-5/eggs/pyScss-1.3.7-py3.9-linux-x86_64.egg/scss/namespace.py:172: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  argspec = inspect.getargspec(function)
/home/arky/Code/Plone/Plone-5/eggs/pyScss-1.3.7-py3.9-linux-x86_64.egg/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
/home/arky/Code/Plone/Plone-5/eggs/eea.facetednavigation-14.7-py3.9.egg/eea/facetednavigation/interfaces.py:3: DeprecationWarning: IObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import IObjectEvent
/home/arky/Code/Plone/Plone-5/eggs/plone.app.imagecropping-2.2.2-py3.9.egg/plone/app/imagecropping/events.py:4: DeprecationWarning: ObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ObjectEvent
/home/arky/Code/Plone/Plone-5/eggs/plone.volto-3.1.0a7-py3.9.egg/plone/volto/vocabularies/subject.py:11: DeprecationWarning: zope.site.hooks has moved to zope.component.hooks. Import of zope.site.hooks will become unsupported in Version 5.0
  from zope.site.hooks import getSite
Traceback (most recent call last):
  File "/home/arky/Code/Plone/Plone-5/eggs/zope.configuration-4.4.0-py3.9.egg/zope/configuration/config.py", line 792, in execute_actions
    callable(*args, **kw)
  File "/home/arky/Code/Plone/Plone-5/eggs/z3c.caching-2.2-py3.9.egg/z3c/caching/zcml.py", line 51, in register
    getGlobalRulesetRegistry().register(for_, ruleset)
  File "/home/arky/Code/Plone/Plone-5/eggs/z3c.caching-2.2-py3.9.egg/z3c/caching/registry.py", line 64, in register
    raise LookupError("Explicit mode set and ruleset %s not found" % rule)
LookupError: Explicit mode set and ruleset plone.content.dynamic not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arky/Code/Plone/Plone-5/parts/instance/bin/interpreter", line 299, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/Startup/serve.py", line 255, in <module>
    sys.exit(main() or 0)
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/Startup/serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/arky/Code/Plone/Plone-5/eggs/PasteDeploy-2.1.1-py3.9.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/arky/Code/Plone/Plone-5/eggs/PasteDeploy-2.1.1-py3.9.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/home/arky/Code/Plone/Plone-5/eggs/PasteDeploy-2.1.1-py3.9.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/arky/Code/Plone/Plone-5/eggs/PasteDeploy-2.1.1-py3.9.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/home/arky/Code/Plone/Plone-5/eggs/PasteDeploy-2.1.1-py3.9.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/arky/Code/Plone/Plone-5/eggs/PasteDeploy-2.1.1-py3.9.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/arky/Code/Plone/Plone-5/eggs/PasteDeploy-2.1.1-py3.9.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/Startup/run.py", line 71, in make_wsgi_app
    starter.prepare()
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/Startup/starter.py", line 99, in startZope
    Zope2.startup_wsgi()
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/App/startup.py", line 143, in startup
    load_zcml()
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/App/startup.py", line 58, in load_zcml
    load_site()
  File "/home/arky/Code/Plone/Plone-5/eggs/Zope-4.6.3-py3.9.egg/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/arky/Code/Plone/Plone-5/eggs/zope.configuration-4.4.0-py3.9.egg/zope/configuration/xmlconfig.py", line 659, in file
    context.execute_actions()
  File "/home/arky/Code/Plone/Plone-5/eggs/zope.configuration-4.4.0-py3.9.egg/zope/configuration/config.py", line 800, in execute_actions
    reraise(ConfigurationExecutionError(info, sys.exc_info()[1]),
  File "/home/arky/Code/Plone/Plone-5/eggs/zope.configuration-4.4.0-py3.9.egg/zope/configuration/_compat.py", line 30, in reraise
    raise value.with_traceback(tb)
  File "/home/arky/Code/Plone/Plone-5/eggs/zope.configuration-4.4.0-py3.9.egg/zope/configuration/config.py", line 792, in execute_actions
    callable(*args, **kw)
  File "/home/arky/Code/Plone/Plone-5/eggs/z3c.caching-2.2-py3.9.egg/z3c/caching/zcml.py", line 51, in register
    getGlobalRulesetRegistry().register(for_, ruleset)
  File "/home/arky/Code/Plone/Plone-5/eggs/z3c.caching-2.2-py3.9.egg/z3c/caching/registry.py", line 64, in register
    raise LookupError("Explicit mode set and ruleset %s not found" % rule)
zope.configuration.config.ConfigurationExecutionError: File "/home/arky/Code/Plone/Plone-5/eggs/collective.volto.dropdownmenu-1.2.0-py3.9.egg/collective/volto/dropdownmenu/restapi/dropdown_menu/configure.zcml", line 15.2-15.78
    <cache:ruleset ruleset="plone.content.dynamic" for=".get.DropDownMenuGet" />

    LookupError: Explicit mode set and ruleset plone.content.dynamic not found

```

Version Overview

    Plone 5.2.6 (5214)
    CMF 2.5.4
    Zope 4.6.3
    Python 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
    PIL 6.2.2 (Pillow)
    WSGI: On
    Server: waitress

**Comment by cekk** [comment]
which version of plone.app.caching are you using?

**Comment by arky** [comment]
I think z3c.caching version 2.2


I have tried to reproduce this with Plone 6-latest but couldn't.

**Comment by erral** [comment]
This happens with Plone 5.2.6 that uses plone.app.caching 2.1.0. Pinning plone.app.caching to 3.0.0a10 (version used in latest Plone 6a2), fixes it.

**Comment by arky** [comment]
Thank you @erral. Pinning to to 3.0.0a10 resoved the issue.
